# Generated by Django 4.2.28 on 2026-02-25 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_project_is_issue_type_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('provider_group', models.CharField(default='', max_length=100)),
                ('cli_tool', models.CharField(max_length=100)),
                ('docker_image', models.CharField(max_length=255)),
                ('oauth_provider', models.CharField(blank=True, max_length=50)),
                ('is_enabled', models.BooleanField(default=False)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'agent_providers',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider_slug', models.CharField(max_length=50)),
                ('variant_slug', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=100)),
                ('skill_trigger', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_text', models.TextField(default='')),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_minutes', models.IntegerField(default=15)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_html', models.TextField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pull_request_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='db.project')),
                ('trigger_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='db.issuecomment')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_agent_sessions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAgentConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('oauth_token_encrypted', models.TextField(blank=True, default='')),
                ('oauth_refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('oauth_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_concurrent_sessions', models.IntegerField(default=3)),
                ('timeout_minutes', models.IntegerField(default=15)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_connections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_configs', to='agent.agentprovider')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_workspace_configs',
                'unique_together': {('workspace', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.SlugField()),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField()),
                ('default_provider', models.CharField(blank=True, default='', max_length=100)),
                ('mode', models.CharField(choices=[('autonomous', 'Autonomous'), ('comment_only', 'Comment Only')], default='autonomous', max_length=20)),
                ('tools', models.JSONField(default=list)),
                ('timeout_minutes', models.IntegerField(default=15)),
                ('context_paths', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_skills', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to='db.workspace')),
            ],
            options={
                'db_table': 'agent_skills',
                'unique_together': {('workspace', 'trigger')},
            },
        ),
        migrations.CreateModel(
            name='AgentProviderVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='agent.agentprovider')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'agent_provider_variants',
                'ordering': ['sort_order'],
                'unique_together': {('provider', 'slug')},
            },
        ),
    ]
