# Generated by Django 4.2.28 on 2026-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_instance_is_current_version_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='edition',
            field=models.CharField(default='PLANE_ENTERPRISE', max_length=255),
        ),
    ]
